/*
 * pal_config.h — NuttX feature flags for System.Native PAL
 *
 * Normally generated by CMake from pal_config.h.in.
 * Hand-written for NuttX cross-compilation (Meadow .NET 10 port).
 */

#pragma once

/* ------------------------------------------------------------------ */
/* NuttX target identification                                        */
/* ------------------------------------------------------------------ */
#ifndef TARGET_UNIX
#define TARGET_UNIX 1
#endif


/* ------------------------------------------------------------------ */
/* File I/O features                                                   */
/* ------------------------------------------------------------------ */
#define HAVE_LSEEK64                0  /* NuttX uses 32-bit off_t */
#define HAVE_MMAP64                 0
#define HAVE_FTRUNCATE64            0
#define HAVE_POSIX_FADVISE64        0
#define HAVE_FLOCK64                0
#define HAVE_STAT64                 0
#define HAVE_F_DUPFD_CLOEXEC        0  /* NuttX may not have F_DUPFD_CLOEXEC */
#define HAVE_F_DUPFD                1
#define HAVE_O_CLOEXEC              0  /* NuttX typically lacks O_CLOEXEC */
#define HAVE_IOCTL                  1
#define HAVE_IOCTL_WITH_INT_REQUEST 1
#define HAVE_TIOCGWINSZ             0  /* No terminal window size ioctl */
#define HAVE_PREADV                 0
#define HAVE_PWRITEV                0

/* ------------------------------------------------------------------ */
/* File system features                                                */
/* ------------------------------------------------------------------ */
#define HAVE_STATFS_VFS             0
#define HAVE_STATFS_MOUNT           0
#define HAVE_STATFS                 0
#define HAVE_NON_LEGACY_STATFS      0
#define HAVE_STATFS_FSTYPENAME      0
#define HAVE_STATVFS_FSTYPENAME     0
#define HAVE_STATVFS_BASETYPE       0
#define HAVE_SYS_STATFS_H          0
#define HAVE_SYS_STATVFS_H         0
#define HAVE_MNTINFO                0
#define HAVE_GETFSSTAT_INT          0
#define HAVE_GETFSSTAT_SIZE_T       0
#define HAVE_GETFSSTAT_LONG         0
#define HAVE_SYS_MNTENT_H          0
#define HAVE_MNTENT_H              0

/* ------------------------------------------------------------------ */
/* Stat structure features                                             */
/* ------------------------------------------------------------------ */
#define HAVE_STAT_BIRTHTIME         0  /* NuttX stat has no birthtime */
#define HAVE_STAT_TIMESPEC          0  /* NuttX stat uses time_t, not timespec */
#define HAVE_STAT_TIM               0
#define HAVE_STAT_NSEC              0
#define HAVE_STAT_FLAGS             0  /* No st_flags on NuttX */
#define HAVE_LCHFLAGS               0
#define HAVE_DIRENT_NAME_LEN        0

/* ------------------------------------------------------------------ */
/* File manipulation                                                   */
/* ------------------------------------------------------------------ */
#define HAVE_CHMOD                  0  /* NuttX has no chmod() */
#define HAVE_FCHMOD                 0  /* NuttX may not have fchmod */
#define HAVE_PIPE                   1
#define HAVE_PIPE2                  0  /* NuttX has pipe but not pipe2 */
#define HAVE_FCOPYFILE              0
#define HAVE_POSIX_ADVISE           0
#define HAVE_FALLOCATE              0
#define HAVE_INOTIFY                0  /* No inotify on NuttX */
#define HAVE_MKSTEMPS               0
#define HAVE_MKSTEMP                0  /* NuttX may not have mkstemp */

/* ------------------------------------------------------------------ */
/* Memory allocation                                                   */
/* ------------------------------------------------------------------ */
#define HAVE_ALIGNED_ALLOC          0  /* NuttX uses memalign, not aligned_alloc */
#define HAVE_POSIX_MEMALIGN         1  /* Provided by mono_nuttx_stubs.c */
#define HAVE_MALLOC_SIZE            0
#define HAVE_MALLOC_USABLE_SIZE     0
#define HAVE_MALLOC_USABLE_SIZE_NP  0

/* ------------------------------------------------------------------ */
/* Process / fork / exec                                               */
/* ------------------------------------------------------------------ */
#define HAVE_FORK                   0  /* NuttX uses task_create instead */
#define HAVE_VFORK                  0

/* ------------------------------------------------------------------ */
/* String handling                                                     */
/* ------------------------------------------------------------------ */
#define HAVE_GNU_STRERROR_R         0  /* NuttX strerror_r is POSIX, not GNU */
#define HAVE_STRCPY_S               0
#define HAVE_STRLCPY                0

/* ------------------------------------------------------------------ */
/* Shared memory                                                       */
/* ------------------------------------------------------------------ */
#define HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP 0

/* ------------------------------------------------------------------ */
/* Scheduler                                                           */
/* ------------------------------------------------------------------ */
#define HAVE_SCHED_GETAFFINITY      0
#define HAVE_SCHED_SETAFFINITY      0
#define HAVE_SCHED_GETCPU           0

/* ------------------------------------------------------------------ */
/* Threading                                                           */
/* ------------------------------------------------------------------ */
#define HAVE_PTHREAD_SETCANCELSTATE 1
#define HAVE_PTHREAD_CONDATTR_SETCLOCK 0  /* Not available in NuttX user space */
#define HAVE_PTHREAD_MUTEX_CLOCKLOCK   0
#define HAVE_PTHREAD_H              1

/* ------------------------------------------------------------------ */
/* Networking                                                          */
/* ------------------------------------------------------------------ */
#define HAVE_GETIFADDRS             0
#define HAVE_UTSNAME_DOMAINNAME     0
#define HAVE_GETHOSTNAME            1
#define HAVE_GETNAMEINFO            0
#define HAVE_GETNAMEINFO_SIGNED_FLAGS 0
#define HAVE_ACCEPT4                0
#define HAVE_SENDFILE_4             0
#define HAVE_SENDFILE_6             0
#define HAVE_SENDFILE_7             0
#define HAVE_SOCKADDR_UN_SUN_PATH   1  /* NuttX has sun_path in sockaddr_un */
#define HAVE_SUPPORT_FOR_DUAL_MODE_IPV4_PACKET_INFO 0
#define HAVE_IN_PKTINFO             1  /* NuttX has struct in_pktinfo */
#define HAVE_IP_MREQN               0
#define HAVE_IP_MULTICAST_IFINDEX   0
#define HAVE_KQUEUE                 0
#define HAVE_EPOLL                  0
#define HAVE_GETPEEREID             0
#define HAVE_GETDOMAINNAME          0
#define HAVE_GETDOMAINNAME_SIZET    0
#define HAVE_DISCONNECTX            0
#define HAVE_CONNECTX               0
#define HAVE_LINUX_RTNETLINK_H      0
#define HAVE_LINUX_CAN_H            0
#define HAVE_LINUX_ERRQUEUE_H       0
#define IPV6MR_INTERFACE_UNSIGNED   0
#define INOTIFY_RM_WATCH_WD_UNSIGNED 0
#define HAVE_IN_EXCL_UNLINK         0
#define HAVE_TCP_H_TCP_KEEPALIVE    0
#define HAVE_SYS_SOCKIO_H          0
#define HAVE_ETHTOOL_H             0
#define HAVE_SYS_POLL_H            0  /* NuttX has poll.h, not sys/poll.h */
#define HAVE_NETPACKET_PACKET_H    0
#define HAVE_NET_IF_ARP_H          0
#define HAVE_NET_IFMEDIA_H         0
#define HAVE_IOS_NET_IFMEDIA_H     0
#define HAVE_NET_IF_H              0
#define HAVE_SYS_SOCKIO_H          0
#define HAVE_TCP_H_TCPSTATE_ENUM   0
#define HAVE_TCP_FSM_H             0
#define HAVE_NETINET_TCP_VAR_H     0
#define HAVE_NETINET_UDP_VAR_H     0
#define HAVE_NETINET_IP_VAR_H      0
#define HAVE_NETINET_ICMP_VAR_H    0
#define HAVE_IOS_NET_ROUTE_H       0
#define HAVE_IOS_NETINET_IP_VAR_H  0
#define HAVE_IOS_NETINET_ICMP_VAR_H 0
#define HAVE_IOS_NETINET_TCPFSM_H  0
#define HAVE_IOS_NETINET_UDP_VAR_H  0
#define HAVE_RT_MSGHDR              0
#define HAVE_RT_MSGHDR2             0
#define HAVE_IF_MSGHDR2             0
#define HAVE_PlatformSupportsDualModeIPv4PacketInfo 0
#define HAVE_GETAUXVAL              0

/* ------------------------------------------------------------------ */
/* Time                                                                */
/* ------------------------------------------------------------------ */
#define HAVE_CLOCK_REALTIME         1
#define HAVE_CLOCK_GETTIME_NSEC_NP  0  /* Apple only */
#define HAVE_UTIMENSAT              0  /* NuttX may not have utimensat */
#define HAVE_LUTIMES                0
#define HAVE_FUTIMES                0
#define HAVE_FUTIMENS               0

/* ------------------------------------------------------------------ */
/* Terminal / serial                                                   */
/* ------------------------------------------------------------------ */
#define HAVE_TERMIOS_H              1
#define HAVE_CFSETSPEED             0
#define HAVE_CFMAKERAW              0
#define HAVE_TERMIOS2               0

/* ------------------------------------------------------------------ */
/* Headers                                                             */
/* ------------------------------------------------------------------ */
#define HAVE_SYSLOG_H               1
#define HAVE_DLFCN_H                1
#define HAVE_GNU_LIBNAMES_H         0
#define HAVE_SYS_SYSCTL_H          0
#define HAVE_SYS_IOCTL_H           1
#define HAVE_SYS_FILIO_H           0
#define HAVE_SYS_PROCINFO_H        0
#define HAVE_IOSS_H                0
#define HAVE_CRT_EXTERNS_H         0
#define HAVE_MAKEDEV_FILEH         0
#define HAVE_MAKEDEV_SYSMACROSH    0

/* ------------------------------------------------------------------ */
/* Misc                                                                */
/* ------------------------------------------------------------------ */
#define HAVE_NSGETENVIRON           0
#define HAVE_BUILTIN_MUL_OVERFLOW   1  /* GCC supports this */
#define PRIORITY_REQUIRES_INT_WHO   0
#define KEVENT_REQUIRES_INT_PARAMS  0
#define KEVENT_HAS_VOID_UDATA       0
#define HAVE_GETGROUPLIST           0
#define HAVE_GETGRGID_R            0
#define HAVE_GSS_SPNEGO_MECHANISM  0
#define HAVE_GSSFW_HEADERS         0
#define HAVE_HEIMDAL_HEADERS       0
#define HAVE_GETGROUPS              0
