/*
 * minipalconfig.h — NuttX minipal configuration
 *
 * Normally generated by CMake from minipalconfig.h.in.
 * Hand-written for NuttX cross-compilation (Meadow .NET 10 port).
 */

#ifndef HAVE_MINIPAL_MINIPALCONFIG_H
#define HAVE_MINIPAL_MINIPALCONFIG_H

#define HAVE_ARC4RANDOM_BUF          0
#define HAVE_GETRANDOM               1
#define HAVE_AUXV_HWCAP_H            0
#define HAVE_HWPROBE_H               0
#define HAVE_RESOURCE_H              1
#define HAVE_O_CLOEXEC               0
#define HAVE_SYSCTLBYNAME            0
#define HAVE_CLOCK_MONOTONIC_COARSE  0
#define HAVE_CLOCK_GETTIME_NSEC_NP   0
#define BIGENDIAN                     0  /* ARM Cortex-M7 is little-endian */
#define HAVE_BCRYPT_H                0
#define HAVE_FSYNC                   1

#endif
